{% set name = "Cfg" %}
{% set tag = "v9r0" %}
{% set version = "9.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ tag }}/{{ name }}-{{ tag }}.tar.gz
  sha256: 3151c52234e1afc5540aad004b28dddf702377c939bf9e68181de6ee9ac86701

build:
  number: 1
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - cm >=9.0.0
  run:
    - cm >=9.0.0

test:
  requires:
    - pkg-config
  commands:
    - test -r ${PREFIX}/lib/libcfg.so
    - pkg-config --print-errors --exact-version ${PKG_VERSION} ${PKG_NAME}  # [unix]

about:
  home: "https://git.ligo.org/virgo/virgoapp/Cfg"
  license: "LGPL-2.1-or-later"
  license_family: GPL
  license_file: COPYING
  summary: "Base library for Virgo processes"
  description: |
    The Cfg package provide a base library for Virgo process 
    configuration parsing, log output and process state 
    management. Cfg is based on the Cm library.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
